package vista.paneles_GestionPedidos;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jpCrearPedidos extends javax.swing.JPanel {

    private final ArrayList<clsTienda> lstTiendas;
    private final ArrayList<clsPedido> lstPedidos;
    
    int pos = -1;
    int posi = 0;
    int pos1 = -1;
    int posi1 = 0;
    int pedido = 0;
    double valorPedido = 0;
    
    public jpCrearPedidos(ArrayList<clsTienda> lstTiendas, ArrayList<clsPedido> lstPedidos) {
        this.lstTiendas = lstTiendas;
        this.lstPedidos = lstPedidos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigoDeFactura = new javax.swing.JLabel();
        txtCodigoDeFactura = new javax.swing.JTextField();
        dcFechaDeFacturacion = new com.toedter.calendar.JDateChooser();
        lblFechaFacturacion = new javax.swing.JLabel();
        lblFechaDePago = new javax.swing.JLabel();
        dcFechaDePago = new com.toedter.calendar.JDateChooser();
        btnBuscarCliente = new javax.swing.JButton();
        lblIDCliente = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        lblCodigoProducto = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        btnRegistrarPedido2 = new javax.swing.JButton();
        lblNOCliente = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblPrecioDelPedido = new javax.swing.JLabel();
        lblPrecioPedido = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Crear pedidos");

        lblCodigoDeFactura.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCodigoDeFactura.setText("Codigo de factura");

        txtCodigoDeFactura.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCodigoDeFactura.setEnabled(false);

        dcFechaDeFacturacion.setEnabled(false);
        dcFechaDeFacturacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        lblFechaFacturacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblFechaFacturacion.setText("Fecha Facturación");

        lblFechaDePago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblFechaDePago.setText("Fecha de pago");

        dcFechaDePago.setEnabled(false);
        dcFechaDePago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        btnBuscarCliente.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblIDCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblIDCliente.setText("ID del Cliente:");

        txtIDCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        btnAgregarProducto.setBackground(new java.awt.Color(0, 153, 255));
        btnAgregarProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.setEnabled(false);
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        lblCodigoProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCodigoProducto.setText("Co. barras del producto:");

        txtCodigoProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtCodigoProducto.setEnabled(false);

        btnRegistrarPedido2.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarPedido2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnRegistrarPedido2.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarPedido2.setText("Registrar");
        btnRegistrarPedido2.setEnabled(false);
        btnRegistrarPedido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPedido2ActionPerformed(evt);
            }
        });

        lblNOCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblNOCliente.setText("Nombre del Cliente:");

        lblNombreCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        lblPrecioDelPedido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblPrecioDelPedido.setText("0");

        lblPrecioPedido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblPrecioPedido.setText("Precio del pedido *sin IVA*:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFechaFacturacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(dcFechaDeFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFechaDePago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dcFechaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodigoDeFactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoDeFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrarPedido2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNOCliente)
                                    .addComponent(lblIDCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoProducto)
                                    .addComponent(lblPrecioPedido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPrecioDelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(92, 92, 92))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDCliente)
                    .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarCliente)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNOCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoDeFactura)
                    .addComponent(txtCodigoDeFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaFacturacion)
                    .addComponent(dcFechaDeFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaDePago)
                    .addComponent(dcFechaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPedido2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoProducto)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioDelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioPedido))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 485, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        try{
            if(this.txtIDCliente.getText().equals("")){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor diligenciar todos los campos.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE
                );
            }
           
            else{
                int IDCliente = Integer.parseInt(this.txtIDCliente.getText());

                for (int i = 0; i < this.lstTiendas.get(0).getLstClientes().size(); i++) {
                    if (IDCliente == (this.lstTiendas.get(0).getLstClientes().get(i).getCedula())) {
                        pos = 0;
                        posi = i;
                        break;
                    }
                }
                
                if (pos==0) {
                JOptionPane.showMessageDialog(this,
                        "Cliente encontrado","Busqueda",
                        JOptionPane.INFORMATION_MESSAGE);
                
                pos = -1;
                
                this.lblPrecioDelPedido.setText("0");
                
                this.lblNombreCliente.setText(this.lstTiendas.get(0).getLstClientes().get(posi).getNombre());
                
                valorPedido = 0;
                
                this.txtCodigoProducto.setEnabled(false);
                this.btnAgregarProducto.setEnabled(false);
                
                this.txtCodigoDeFactura.setEnabled(true);
                this.dcFechaDeFacturacion.setEnabled(true);
                this.dcFechaDePago.setEnabled(true);
                this.btnRegistrarPedido2.setEnabled(true);
                }
            
                else{
                    JOptionPane.showMessageDialog(this,
                        "Cliente no encontrado","Busqueda",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "Error al ingresar datos númericos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(this,
                    "No hay espacio para guardar datos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }

        catch (HeadlessException e){            
               JOptionPane.showMessageDialog(this,
                    "Error interno en el programa."+e.getMessage(),
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.txtIDCliente.setText(""); 
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        try{
            if(this.txtCodigoProducto.getText().equals("")){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor diligenciar todos los campos.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE
                );
            }
           
            else{
                int CodigoProducto = Integer.parseInt(this.txtCodigoProducto.getText());

                for (int i = 0; i < this.lstTiendas.get(0).getLstProductos().size(); i++) {
                    if (CodigoProducto == (this.lstTiendas.get(0).getLstProductos().get(i).getCodigoBarras())) {
                        pos1 = 0;
                        posi1 = i;
                        break;
                    }
                }
                
                if (pos1==0) {
                JOptionPane.showMessageDialog(this,
                        "Producto " + this.lstTiendas.get(0).getLstProductos().get(posi1).getNombre() + " agregado","Busqueda",
                        JOptionPane.INFORMATION_MESSAGE);
                
                this.lstTiendas.get(0).getLstClientes().get(posi).getLstPedidos().get(pedido).agregarProducto(this.lstTiendas.get(0).getLstProductos().get(posi1));
                
                pos1 = -1;

                valorPedido = valorPedido + this.lstTiendas.get(0).getLstClientes().get(posi).getLstPedidos().get(pedido).getLstProductos().get(0).getPrecio();
                
                this.lstTiendas.get(0).getLstClientes().get(posi).getLstPedidos().get(pedido).setValorPedido(valorPedido);
                
                String str = String.valueOf(valorPedido);
                
                this.lblPrecioDelPedido.setText(str);
                
                this.txtCodigoDeFactura.setEnabled(true);
                this.dcFechaDeFacturacion.setEnabled(true);
                this.dcFechaDePago.setEnabled(true);
                this.btnRegistrarPedido2.setEnabled(true);
                }
            
                else{
                    JOptionPane.showMessageDialog(this,
                        "Producto no encontrado","Busqueda",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "Error al ingresar datos númericos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.txtCodigoProducto.setText(""); 
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnRegistrarPedido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPedido2ActionPerformed
        try{
            if(this.txtCodigoDeFactura.getText().equals("")){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor diligenciar todos los campos.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE
                );
            }
           
            else{
                pedido = this.lstTiendas.get(0).getLstClientes().get(posi).getLstPedidos().size();
                long codigodefactura = Long.parseLong(this.txtCodigoDeFactura.getText());
                Calendar fechafac = this.dcFechaDeFacturacion.getCalendar();
                Calendar fechapag = this.dcFechaDePago.getCalendar();
                
                double total = 0;

                clsPedido objPedido = new clsPedido(codigodefactura,fechafac,fechapag,total);
                
                this.lstPedidos.add(objPedido);
                System.out.println(posi);
                this.lstTiendas.get(0).getLstClientes().get(posi).agregarPedido(objPedido);
                
                valorPedido = 0;
                
                this.lblPrecioDelPedido.setText("0");
                JOptionPane.showMessageDialog(this,
                        "Pedido Creado","Registro exitoso",
                        JOptionPane.INFORMATION_MESSAGE);
                
                this.txtCodigoProducto.setEnabled(true);
                this.btnAgregarProducto.setEnabled(true);
            }
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "Error al ingresar datos númericos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.txtCodigoDeFactura.setText("");
            this.dcFechaDeFacturacion.setCalendar(null);
            this.dcFechaDePago.setCalendar(null);
        }
    }//GEN-LAST:event_btnRegistrarPedido2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnRegistrarPedido2;
    private com.toedter.calendar.JDateChooser dcFechaDeFacturacion;
    private com.toedter.calendar.JDateChooser dcFechaDePago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigoDeFactura;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblFechaDePago;
    private javax.swing.JLabel lblFechaFacturacion;
    private javax.swing.JLabel lblIDCliente;
    private javax.swing.JLabel lblNOCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblPrecioDelPedido;
    private javax.swing.JLabel lblPrecioPedido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigoDeFactura;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtIDCliente;
    // End of variables declaration//GEN-END:variables
}
