package vista.paneles_GestionPedidos;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jpEliminarPedido extends javax.swing.JPanel {

    private final ArrayList<clsTienda> lstTiendas;
    private final ArrayList<clsPedido> lstPedidos;
    
    int pos = -1;
    int posi = 0;
    int aux = -1;
    
    public jpEliminarPedido(ArrayList<clsTienda> lstTiendas, ArrayList<clsPedido> lstPedidos) {
        this.lstTiendas = lstTiendas;
        this.lstPedidos = lstPedidos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigodeFactura = new javax.swing.JLabel();
        txtCodigodeDeFactura = new javax.swing.JTextField();
        lblCodigoProducto = new javax.swing.JLabel();
        btnBuscarPedido = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        btnEliminarPedido = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Eliminar pedido");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        lblCodigodeFactura.setBackground(new java.awt.Color(0, 0, 0));
        lblCodigodeFactura.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCodigodeFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigodeFactura.setText("Codigo de factura:");
        jPanel1.add(lblCodigodeFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, -1));

        txtCodigodeDeFactura.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jPanel1.add(txtCodigodeDeFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 150, -1));

        lblCodigoProducto.setBackground(new java.awt.Color(0, 0, 0));
        lblCodigoProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCodigoProducto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 160, 20));

        btnBuscarPedido.setBackground(new java.awt.Color(51, 153, 255));
        btnBuscarPedido.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnBuscarPedido.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarPedido.setText("Buscar");
        btnBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        lblCodigo.setBackground(new java.awt.Color(0, 0, 0));
        lblCodigo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("Codigo:");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, -1));

        btnEliminarPedido.setBackground(new java.awt.Color(51, 153, 255));
        btnEliminarPedido.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnEliminarPedido.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarPedido.setText("Eliminar");
        btnEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPedidoActionPerformed
        try{
            if(this.txtCodigodeDeFactura.getText().equals("")){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor diligenciar todos los campos.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE
                );
            }
           
            else{
                int codigoFactura = Integer.parseInt(this.txtCodigodeDeFactura.getText());
                
                for (int i = 0; i < this.lstPedidos.size(); i++) {
                    if (codigoFactura == (this.lstPedidos.get(i).getCodigoFactura())) {
                        aux = i;
                        pos = 0;
                        posi = i;
                        String str = String.valueOf(this.lstPedidos.get(i).getCodigoFactura()); 
                        this.lblCodigoProducto.setText(str);
                        break;
                    }
                }
                
                if (pos==0) {
                JOptionPane.showMessageDialog(this,
                        "Pedido encontrado","Busqueda",
                        JOptionPane.INFORMATION_MESSAGE);
                
                pos = -1;
                
                }
            
                else{
                    JOptionPane.showMessageDialog(this,
                        "Pedido no encontrado","Busqueda",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "Error al ingresar datos númericos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(this,
                    "No hay espacio para guardar datos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }

        catch (HeadlessException e){            
               JOptionPane.showMessageDialog(this,
                    "Error interno en el programa."+e.getMessage(),
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.txtCodigodeDeFactura.setText(""); 
        }
    }//GEN-LAST:event_btnBuscarPedidoActionPerformed

    private void btnEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidoActionPerformed
        try{
            this.lstPedidos.remove(aux);
            
            aux = -1;
            
            this.lblCodigoProducto.setText("");
            JOptionPane.showMessageDialog(this,
                        "Pedido eliminado","Busqueda",
                        JOptionPane.INFORMATION_MESSAGE);
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "Error al ingresar datos númericos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        catch (ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,
                    "Ingresa un pedido primero.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPedido;
    private javax.swing.JButton btnEliminarPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblCodigodeFactura;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigodeDeFactura;
    // End of variables declaration//GEN-END:variables
}
