package vista.paneles_GestionPedidos;

import datos.GestionArchivo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jpImprimirPedidos extends javax.swing.JPanel {

    private final ArrayList<clsTienda> lstTiendas;
    private final ArrayList<clsPedido> lstPedidos;
    
    
    int aux = 0;
    int aux1 = -1;
    int aux2 = 0;
    
    public jpImprimirPedidos(ArrayList<clsTienda> lstTiendas, ArrayList<clsPedido> lstPedidos) {
        this.lstTiendas = lstTiendas;
        this.lstPedidos = lstPedidos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnImprimirPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        btnGuardarArchivo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Imprimir Pedidos");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        btnImprimirPedido.setBackground(new java.awt.Color(51, 153, 255));
        btnImprimirPedido.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnImprimirPedido.setForeground(new java.awt.Color(0, 0, 0));
        btnImprimirPedido.setText("Imprimir");
        btnImprimirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        tablaPedidos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Co. Factura", "Fe. Facturación", "Fe. Pago", "Va.Pedido*Sin IVA*"
            }
        ));
        jScrollPane1.setViewportView(tablaPedidos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 450, 300));

        btnGuardarArchivo.setBackground(new java.awt.Color(0, 153, 255));
        btnGuardarArchivo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnGuardarArchivo.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarArchivo.setText("Guardar en archivo");
        btnGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPedidoActionPerformed
        aux2 = 0;
        for (int k = 0; k < this.lstPedidos.size(); k++) {
            if (this.lstPedidos.size() > 0) {
                aux2 = 1;
                aux1 = -1;
                
                for (int i = 0; i < this.lstPedidos.size(); i++) {
                    aux = aux + 1;
                }

                Object matriz [][] = new Object[aux][4];

                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

                for (int i = 0; i < this.lstPedidos.size(); i++) {
                    aux1 = aux1 + 1;
                    
                    String fechafab = formato.format(this.lstPedidos.get(i).getFechaFacturacion().getTime());
                    String fechapa = formato.format(this.lstPedidos.get(i).getFechaPago().getTime());
                    
                    matriz[aux1][0] = this.lstPedidos.get(i).getCodigoFactura();
                    matriz[aux1][1] = fechafab;
                    matriz[aux1][2] = fechapa;
                    matriz[aux1][3] = this.lstPedidos.get(i).getValorPedido();
                }
                aux = 0;

                tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String [] {"Co. Factura", "Fe. Facturación", "Fe. Pago", "Val. Pedido *Sin IVA*"}
                ));
            }
        }
        
        if(aux2 == 0){
            DefaultTableModel model = (DefaultTableModel) tablaPedidos.getModel(); 
            model.setRowCount(0);

                JOptionPane.showMessageDialog(this,
                        "No hay pedidos, crea uno primero.",
                        "Validación.",
                        JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnImprimirPedidoActionPerformed

    private void btnGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArchivoActionPerformed
        GestionArchivo GA = new GestionArchivo();
        GA.escribirDatosPedidos(this.lstTiendas);

        JOptionPane.showMessageDialog(null,
            "Datos guardados con éxito.",
            "Gestión escritura",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGuardarArchivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarArchivo;
    private javax.swing.JButton btnImprimirPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
}
