package vista.paneles_GestionPersonas;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jpCrearEmpleados extends javax.swing.JPanel {

    private final ArrayList<clsTienda> lstTiendas;
    
    public jpCrearEmpleados(ArrayList<clsTienda> lstTiendas) {
        this.lstTiendas = lstTiendas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre9 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtCedulaEmpleado = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox<>();
        txtExperiencia = new javax.swing.JTextField();
        lblSueldo1 = new javax.swing.JLabel();
        btnRegistrarEmpleado = new javax.swing.JButton();
        lblSueldo = new javax.swing.JLabel();
        txtSueldoEmpleado = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Crear empleados");

        lblNombre9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblNombre9.setText("Nombre:");

        txtNombreEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        txtCedulaEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        lblCedula.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCedula.setText("Cedula:");

        lblCargo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCargo.setText("Cargo:");

        cbCargo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        cbCargo.setModel(new DefaultComboBoxModel(tipoCargo.values()));

        txtExperiencia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        lblSueldo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblSueldo1.setText("Experiencia:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                                .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCargo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                                .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSueldo1)
                        .addGap(145, 145, 145)
                        .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre9)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSueldo1)
                    .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 485, -1));

        btnRegistrarEmpleado.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnRegistrarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarEmpleado.setText("Registrar");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });
        add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        lblSueldo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblSueldo.setText("Sueldo:");
        add(lblSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        txtSueldoEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        add(txtSueldoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        try{
            if(this.txtNombreEmpleado.getText().equals("") ||
                this.txtCedulaEmpleado.getText().equals("") ||
                this.txtExperiencia.getText().equals("") ||
                this.txtSueldoEmpleado.getText().equals("")){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor diligenciar todos los campos.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        
            else{
                String nombre = this.txtNombreEmpleado.getText();
                long cedula = Long.parseLong(this.txtCedulaEmpleado.getText());
                int sueldo = Integer.parseInt(this.txtSueldoEmpleado.getText());
                String experiencia = this.txtExperiencia.getText();
                int posCargo = this.cbCargo.getSelectedIndex();
                tipoCargo aux;

                if(posCargo==0){
                    aux = tipoCargo.Auxiliar;
                }
                else{
                    if(posCargo==1){
                        aux = tipoCargo.Cajero;
                    }
                    else{
                        if(posCargo==2){
                            aux = tipoCargo.Coordinador;
                        }
                        else{
                            aux = tipoCargo.Jefe;
                        }
                    }
                }
                
                this.lstTiendas.get(0).crearEmpleado(nombre, cedula, aux, experiencia, sueldo);

                JOptionPane.showMessageDialog(this,
                        "Empleado Creado","Registro exitoso",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "Error al ingresar datos númericos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(this,
                    "No hay espacio para guardar datos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }

        catch (HeadlessException e){            
               JOptionPane.showMessageDialog(this,
                    "Error interno en el programa."+e.getMessage(),
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.txtNombreEmpleado.setText("");
            this.txtCedulaEmpleado.setText("");
            this.cbCargo.setSelectedIndex(0);
            this.txtSueldoEmpleado.setText("");
            this.txtExperiencia.setText("");
        }
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombre9;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JLabel lblSueldo1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCedulaEmpleado;
    private javax.swing.JTextField txtExperiencia;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtSueldoEmpleado;
    // End of variables declaration//GEN-END:variables
}
