package vista.paneles_GestionPersonas;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jpCrearClientes extends javax.swing.JPanel {

    private final ArrayList<clsTienda> lstTiendas;
    private final ArrayList<clsCliente> lstCliente;
    
    public jpCrearClientes(ArrayList<clsTienda> lstTiendas, ArrayList<clsCliente> lstCliente) {
        this.lstTiendas = lstTiendas;
        this.lstCliente = lstCliente;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccionClientes = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefonoClientes = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Crear clientes");

        lblNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombreCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        txtCedulaCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        lblCedula.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCedula.setText("Cedula:");

        lblDireccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDireccion.setText("Direccion");

        txtDireccionClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        lblTelefono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblTelefono.setText("Telefono");

        txtTelefonoClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDireccionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelefonoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTelefonoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 485, -1));

        btnRegistrarCliente.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarCliente.setText("Registrar");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        try{
            if(this.txtNombreCliente.getText().equals("") ||
                this.txtCedulaCliente.getText().equals("") || 
                this.txtDireccionClientes.getText().equals("") ||
                this.txtTelefonoClientes.getText().equals("")){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor diligenciar todos los campos.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        
            else{
                String nombre = this.txtNombreCliente.getText();
                long cedula = Long.parseLong(this.txtCedulaCliente.getText());
                String direccion = this.txtDireccionClientes.getText();
                long telefono = Long.parseLong(this.txtTelefonoClientes.getText());
                
                clsCliente objCliente = new clsCliente(nombre, cedula, direccion, telefono);
                
                this.lstCliente.add(objCliente);
                
                this.lstTiendas.get(0).agregarCliente(objCliente);

                JOptionPane.showMessageDialog(this,
                        "Cliente Creado","Registro exitoso",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }    
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "Error al ingresar datos númericos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(this,
                    "No hay espacio para guardar datos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }

        catch (HeadlessException e){            
               JOptionPane.showMessageDialog(this,
                    "Error interno en el programa."+e.getMessage(),
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        finally{
            this.txtNombreCliente.setText("");
            this.txtCedulaCliente.setText("");
            this.txtDireccionClientes.setText("");
            this.txtTelefonoClientes.setText("");
        }
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtDireccionClientes;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoClientes;
    // End of variables declaration//GEN-END:variables
}
