package vista.paneles_GestionPersonas;

import datos.GestionArchivo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jpImprimirEmpleados extends javax.swing.JPanel {

    private final ArrayList<clsTienda> lstTiendas;
    
    public jpImprimirEmpleados(ArrayList<clsTienda> lstTiendas) {
        this.lstTiendas = lstTiendas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnImprimirEmpleados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        btnGuardarArchivo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Imprimir empleados");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        btnImprimirEmpleados.setBackground(new java.awt.Color(51, 153, 255));
        btnImprimirEmpleados.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnImprimirEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnImprimirEmpleados.setText("Imprimir");
        btnImprimirEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        tablaEmpleados.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula", "Cargo", "Sueldo", "Experiencia"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 430, 300));

        btnGuardarArchivo.setBackground(new java.awt.Color(0, 153, 255));
        btnGuardarArchivo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnGuardarArchivo.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarArchivo.setText("Guardar en archivo");
        btnGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirEmpleadosActionPerformed
        if (this.lstTiendas.get(0).getLstEmpleados().size() > 0) {
            Object matriz [][] = new Object[this.lstTiendas.get(0).getLstEmpleados().size()][5];

            for(int i=0; i< this.lstTiendas.get(0).getLstEmpleados().size(); i++){
                matriz[i][0] = this.lstTiendas.get(0).getLstEmpleados().get(i).getNombre();
                matriz[i][1] = this.lstTiendas.get(0).getLstEmpleados().get(i).getCedula();
                matriz[i][2] = this.lstTiendas.get(0).getLstEmpleados().get(i).getCargo();
                matriz[i][3] = this.lstTiendas.get(0).getLstEmpleados().get(i).getSueldo();
                matriz[i][4] = this.lstTiendas.get(0).getLstEmpleados().get(i).getExperiencia();
            }

            tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String [] {"Nombre", "Cedula", "Cargo", "Sueldo", "Experiencia"}
            ));
        }
        else{
            JOptionPane.showMessageDialog(this,
                    "Crea un empleado primero.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImprimirEmpleadosActionPerformed

    private void btnGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArchivoActionPerformed
        GestionArchivo GA = new GestionArchivo();
        GA.escribirDatosEmpleados(this.lstTiendas);

        JOptionPane.showMessageDialog(null,
            "Datos guardados con éxito.",
            "Gestión escritura",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGuardarArchivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarArchivo;
    private javax.swing.JButton btnImprimirEmpleados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}
