package vista;

import java.awt.BorderLayout;
import java.util.ArrayList;
import modelo.*;
import vista.paneles_GestionPersonas.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jDialogGestionPersonas extends javax.swing.JDialog {
    
    private final ArrayList<clsTienda> lstTiendas;
    private final ArrayList<clsCliente> lstClientes;
    private final jpCrearEmpleados panelCrearEmpleados ;
    private final jpCrearClientes panelCrearClientes;
    private final jpImprimirClientes panelImprimirClientes;
    private final jpImprimirEmpleados panelImprimirEmpleados;
    
    public jDialogGestionPersonas(java.awt.Frame parent, boolean modal, ArrayList<clsTienda> lstTiendas, ArrayList<clsCliente> lstClientes) {
        super(parent, modal);
        this.lstTiendas = lstTiendas;
        this.lstClientes = lstClientes;
        this.panelCrearEmpleados = new jpCrearEmpleados(this.lstTiendas);
        this.panelCrearClientes = new jpCrearClientes(this.lstTiendas,this.lstClientes);
        this.panelImprimirClientes = new jpImprimirClientes(this.lstTiendas);
        this.panelImprimirEmpleados = new jpImprimirEmpleados(this.lstTiendas);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCrearClientes = new javax.swing.JButton();
        btnImprimirEmpleados = new javax.swing.JButton();
        lblClientes = new javax.swing.JLabel();
        lblEmpleados = new javax.swing.JLabel();
        btnImprimirClientes = new javax.swing.JButton();
        btnCrearEmpleados = new javax.swing.JButton();
        jPanelCentro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(680, 590));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(877, 110));
        jPanel1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Gestión de personas");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(140, 30, 421, 43);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen12.png"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(677, 280));
        jPanel1.add(Logo);
        Logo.setBounds(10, -170, 650, 290);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(180, 380));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearClientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCrearClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen14.png"))); // NOI18N
        btnCrearClientes.setToolTipText("");
        btnCrearClientes.setBorder(null);
        btnCrearClientes.setBorderPainted(false);
        btnCrearClientes.setContentAreaFilled(false);
        btnCrearClientes.setFocusPainted(false);
        btnCrearClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrearClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 90));

        btnImprimirEmpleados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImprimirEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen15.png"))); // NOI18N
        btnImprimirEmpleados.setToolTipText("");
        btnImprimirEmpleados.setBorder(null);
        btnImprimirEmpleados.setBorderPainted(false);
        btnImprimirEmpleados.setContentAreaFilled(false);
        btnImprimirEmpleados.setFocusPainted(false);
        btnImprimirEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimirEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 90));

        lblClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(0, 0, 0));
        lblClientes.setText("Clientes");
        jPanel2.add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblEmpleados.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        lblEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleados.setText("Empleados");
        jPanel2.add(lblEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        btnImprimirClientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImprimirClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen15.png"))); // NOI18N
        btnImprimirClientes.setToolTipText("");
        btnImprimirClientes.setBorder(null);
        btnImprimirClientes.setBorderPainted(false);
        btnImprimirClientes.setContentAreaFilled(false);
        btnImprimirClientes.setFocusPainted(false);
        btnImprimirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimirClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 90));

        btnCrearEmpleados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCrearEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen14.png"))); // NOI18N
        btnCrearEmpleados.setToolTipText("");
        btnCrearEmpleados.setBorder(null);
        btnCrearEmpleados.setBorderPainted(false);
        btnCrearEmpleados.setContentAreaFilled(false);
        btnCrearEmpleados.setFocusPainted(false);
        btnCrearEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrearEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 90));

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanelCentro.setBackground(new java.awt.Color(240, 240, 240));
        jPanelCentro.setForeground(new java.awt.Color(240, 240, 240));
        jPanelCentro.setPreferredSize(new java.awt.Dimension(310, 370));
        jPanelCentro.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClientesActionPerformed
        this.jPanelCentro.remove(this.panelCrearEmpleados);
        this.jPanelCentro.remove(this.panelImprimirClientes);
        this.jPanelCentro.remove(this.panelImprimirEmpleados);
        this.jPanelCentro.add(this.panelCrearClientes,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnCrearClientesActionPerformed

    private void btnImprimirEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirEmpleadosActionPerformed
        this.jPanelCentro.remove(this.panelCrearEmpleados);
        this.jPanelCentro.remove(this.panelImprimirClientes);
        this.jPanelCentro.remove(this.panelCrearClientes);
        this.jPanelCentro.add(this.panelImprimirEmpleados,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnImprimirEmpleadosActionPerformed

    private void btnImprimirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirClientesActionPerformed
        this.jPanelCentro.remove(this.panelCrearEmpleados);
        this.jPanelCentro.remove(this.panelCrearClientes);
        this.jPanelCentro.remove(this.panelImprimirEmpleados);
        this.jPanelCentro.add(this.panelImprimirClientes,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnImprimirClientesActionPerformed

    private void btnCrearEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEmpleadosActionPerformed
        this.jPanelCentro.remove(this.panelCrearClientes);
        this.jPanelCentro.remove(this.panelImprimirClientes);
        this.jPanelCentro.remove(this.panelImprimirEmpleados);
        this.jPanelCentro.add(this.panelCrearEmpleados,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnCrearEmpleadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnCrearClientes;
    private javax.swing.JButton btnCrearEmpleados;
    private javax.swing.JButton btnImprimirClientes;
    private javax.swing.JButton btnImprimirEmpleados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}