package vista;

import java.awt.BorderLayout;
import java.util.ArrayList;
import modelo.*;
import vista.paneles_GestionProductos.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jDialogGestionProductos extends javax.swing.JDialog {
    
    private final ArrayList<clsTienda> lstTiendas;
    private final jpCrearProducto panelProducto;
    private final jpEliminarProducto panelEliminarProducto;
    private final jpFiltrarMenorPrecio panelFiltrarMenorPrecio;
    private final jpImprimirProductos panelImprimirProductos;
    
    public jDialogGestionProductos(java.awt.Frame parent, boolean modal, ArrayList<clsTienda> lstTiendas) {
        super(parent, modal);
        
        this.lstTiendas = lstTiendas;
        this.panelProducto = new jpCrearProducto(this.lstTiendas);
        this.panelEliminarProducto = new jpEliminarProducto(this.lstTiendas);
        this.panelFiltrarMenorPrecio = new jpFiltrarMenorPrecio(this.lstTiendas);
        this.panelImprimirProductos = new jpImprimirProductos(this.lstTiendas);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCrearProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnImprimirProducto = new javax.swing.JButton();
        btnFiltrarMenorPrecio = new javax.swing.JButton();
        jPanelCentro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(680, 590));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(877, 110));
        jPanel1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Gestión de productos");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(130, 30, 421, 43);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen12.png"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(677, 280));
        jPanel1.add(Logo);
        Logo.setBounds(10, -170, 650, 290);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(180, 380));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCrearProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen14.png"))); // NOI18N
        btnCrearProducto.setToolTipText("");
        btnCrearProducto.setBorder(null);
        btnCrearProducto.setBorderPainted(false);
        btnCrearProducto.setContentAreaFilled(false);
        btnCrearProducto.setFocusPainted(false);
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrearProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 90));

        btnEliminarProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen13.png"))); // NOI18N
        btnEliminarProducto.setToolTipText("");
        btnEliminarProducto.setBorder(null);
        btnEliminarProducto.setBorderPainted(false);
        btnEliminarProducto.setContentAreaFilled(false);
        btnEliminarProducto.setFocusPainted(false);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, -1));

        btnImprimirProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImprimirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen15.png"))); // NOI18N
        btnImprimirProducto.setToolTipText("");
        btnImprimirProducto.setBorder(null);
        btnImprimirProducto.setBorderPainted(false);
        btnImprimirProducto.setContentAreaFilled(false);
        btnImprimirProducto.setFocusPainted(false);
        btnImprimirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 90));

        btnFiltrarMenorPrecio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFiltrarMenorPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen16.png"))); // NOI18N
        btnFiltrarMenorPrecio.setToolTipText("");
        btnFiltrarMenorPrecio.setBorder(null);
        btnFiltrarMenorPrecio.setBorderPainted(false);
        btnFiltrarMenorPrecio.setContentAreaFilled(false);
        btnFiltrarMenorPrecio.setFocusPainted(false);
        btnFiltrarMenorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarMenorPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(btnFiltrarMenorPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 90));

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanelCentro.setBackground(new java.awt.Color(240, 240, 240));
        jPanelCentro.setForeground(new java.awt.Color(240, 240, 240));
        jPanelCentro.setPreferredSize(new java.awt.Dimension(310, 370));
        jPanelCentro.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        this.jPanelCentro.remove(this.panelEliminarProducto);
        this.jPanelCentro.remove(this.panelFiltrarMenorPrecio);
        this.jPanelCentro.remove(this.panelImprimirProductos);
        this.jPanelCentro.add(this.panelProducto,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        this.jPanelCentro.remove(this.panelProducto);
        this.jPanelCentro.remove(this.panelFiltrarMenorPrecio);
        this.jPanelCentro.remove(this.panelImprimirProductos);
        this.jPanelCentro.add(this.panelEliminarProducto,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnFiltrarMenorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarMenorPrecioActionPerformed
        this.jPanelCentro.remove(this.panelEliminarProducto);
        this.jPanelCentro.remove(this.panelProducto);
        this.jPanelCentro.remove(this.panelImprimirProductos);
        this.jPanelCentro.add(this.panelFiltrarMenorPrecio,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnFiltrarMenorPrecioActionPerformed

    private void btnImprimirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirProductoActionPerformed
        this.jPanelCentro.remove(this.panelEliminarProducto);
        this.jPanelCentro.remove(this.panelFiltrarMenorPrecio);
        this.jPanelCentro.remove(this.panelProducto);
        this.jPanelCentro.add(this.panelImprimirProductos,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnImprimirProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnFiltrarMenorPrecio;
    private javax.swing.JButton btnImprimirProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}