package vista;

import java.util.ArrayList;
import modelo.*;
/**
 *
 * @author Pablo Restrepo
 */
public class vtnPrincipal extends javax.swing.JFrame {

    private final ArrayList<clsTienda> lstTiendas;
    private final ArrayList<clsPedido> lstPedidos;
    private final ArrayList<clsCliente> lstClientes;
    
    public vtnPrincipal(ArrayList<clsTienda> lstTiendas, ArrayList<clsPedido> lstPedidos, ArrayList<clsCliente> lstClientes) {
        this.lstTiendas = lstTiendas;
        this.lstPedidos = lstPedidos;
        this.lstClientes = lstClientes;
        
        clsTienda objTienda = new clsTienda("Justo y Bueno","CRA6 No.5-9",8234378,"La Paz");
        
        this.lstTiendas.add(objTienda);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCentral = new javax.swing.JPanel();
        btnGetionPedidos1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGetionProductos1 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnGetionPersonas1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCentral.setBackground(new java.awt.Color(240, 240, 240));
        jpCentral.setForeground(new java.awt.Color(204, 204, 204));
        jpCentral.setPreferredSize(new java.awt.Dimension(677, 587));
        jpCentral.setLayout(null);

        btnGetionPedidos1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGetionPedidos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen3.png"))); // NOI18N
        btnGetionPedidos1.setBorder(null);
        btnGetionPedidos1.setBorderPainted(false);
        btnGetionPedidos1.setContentAreaFilled(false);
        btnGetionPedidos1.setFocusPainted(false);
        btnGetionPedidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetionPedidos1ActionPerformed(evt);
            }
        });
        jpCentral.add(btnGetionPedidos1);
        btnGetionPedidos1.setBounds(10, 410, 300, 154);

        btnSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen5.png"))); // NOI18N
        btnSalir.setToolTipText("");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpCentral.add(btnSalir);
        btnSalir.setBounds(380, 410, 310, 154);

        btnGetionProductos1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGetionProductos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen1.png"))); // NOI18N
        btnGetionProductos1.setToolTipText("");
        btnGetionProductos1.setBorder(null);
        btnGetionProductos1.setBorderPainted(false);
        btnGetionProductos1.setContentAreaFilled(false);
        btnGetionProductos1.setFocusPainted(false);
        btnGetionProductos1.setMaximumSize(new java.awt.Dimension(497, 237));
        btnGetionProductos1.setMinimumSize(new java.awt.Dimension(497, 237));
        btnGetionProductos1.setName(""); // NOI18N
        btnGetionProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetionProductos1ActionPerformed(evt);
            }
        });
        jpCentral.add(btnGetionProductos1);
        btnGetionProductos1.setBounds(10, 240, 300, 154);

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen4.png"))); // NOI18N
        jpCentral.add(lblTitulo);
        lblTitulo.setBounds(13, -50, 660, 270);

        btnGetionPersonas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGetionPersonas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen2.png"))); // NOI18N
        btnGetionPersonas1.setToolTipText("");
        btnGetionPersonas1.setBorder(null);
        btnGetionPersonas1.setBorderPainted(false);
        btnGetionPersonas1.setContentAreaFilled(false);
        btnGetionPersonas1.setFocusPainted(false);
        btnGetionPersonas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetionPersonas1ActionPerformed(evt);
            }
        });
        jpCentral.add(btnGetionPersonas1);
        btnGetionPersonas1.setBounds(370, 240, 300, 154);

        getContentPane().add(jpCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetionPedidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetionPedidos1ActionPerformed
        jDialogGestionPedidos jdGestionPedidos = new jDialogGestionPedidos(this,false,this.lstTiendas,this.lstPedidos);
        jdGestionPedidos.setVisible(true);
    }//GEN-LAST:event_btnGetionPedidos1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGetionProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetionProductos1ActionPerformed
        jDialogGestionProductos jdGestionProductos = new jDialogGestionProductos(this,false,this.lstTiendas);
        jdGestionProductos.setVisible(true);
    }//GEN-LAST:event_btnGetionProductos1ActionPerformed

    private void btnGetionPersonas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetionPersonas1ActionPerformed
        jDialogGestionPersonas jdGestionPersonas = new jDialogGestionPersonas(this,false,this.lstTiendas,this.lstClientes);
        jdGestionPersonas.setVisible(true);
    }//GEN-LAST:event_btnGetionPersonas1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetionPedidos1;
    private javax.swing.JButton btnGetionPersonas1;
    private javax.swing.JButton btnGetionProductos1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jpCentral;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}