package vista.paneles_GestionProductos;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jpCrearProducto extends javax.swing.JPanel {

    private final ArrayList<clsTienda> lstTiendas;
    
    public jpCrearProducto(ArrayList<clsTienda> lstTiendas) {
        this.lstTiendas = lstTiendas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigodeBarras = new javax.swing.JLabel();
        txtCodigodeBarras = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblFechaven = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblFechafab = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        dcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        dcFechaFabricacion = new com.toedter.calendar.JDateChooser();
        btnCrearProducto = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Crear producto");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        lblCodigodeBarras.setBackground(new java.awt.Color(0, 0, 0));
        lblCodigodeBarras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCodigodeBarras.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigodeBarras.setText("Codigo de barras:");
        jPanel1.add(lblCodigodeBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, -1));

        txtCodigodeBarras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jPanel1.add(txtCodigodeBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 150, -1));

        txtNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, -1));

        lblNombre.setBackground(new java.awt.Color(0, 0, 0));
        lblNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, -1));

        lblFechaven.setBackground(new java.awt.Color(0, 0, 0));
        lblFechaven.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblFechaven.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaven.setText("Fecha de vencimiento:");
        jPanel1.add(lblFechaven, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, -1));

        txtPrecio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 150, -1));

        lblFechafab.setBackground(new java.awt.Color(0, 0, 0));
        lblFechafab.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblFechafab.setForeground(new java.awt.Color(0, 0, 0));
        lblFechafab.setText("Fecha de fabricacion:");
        jPanel1.add(lblFechafab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 200, -1));

        lblPrecio.setBackground(new java.awt.Color(0, 0, 0));
        lblPrecio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecio.setText("Precio:");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, -1));

        dcFechaVencimiento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jPanel1.add(dcFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, -1));

        dcFechaFabricacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jPanel1.add(dcFechaFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 150, -1));

        btnCrearProducto.setBackground(new java.awt.Color(51, 153, 255));
        btnCrearProducto.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnCrearProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearProducto.setText("Crear");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        try{
            if(this.txtCodigodeBarras.getText().equals("") ||
                this.txtNombre.getText().equals("") || 
                this.txtPrecio.getText().equals("") ||
                this.txtCodigodeBarras.getText().equals("")){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor diligenciar todos los campos.",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE
                );
            }
           
            else{
                long codigodebarras = Long.parseLong(this.txtCodigodeBarras.getText());
                String nombre = this.txtNombre.getText();
                Calendar fechaven = this.dcFechaVencimiento.getCalendar();
                Calendar fechafab = this.dcFechaFabricacion.getCalendar();
                double precio = Double.parseDouble(this.txtPrecio.getText());

                this.lstTiendas.get(0).crearProducto(codigodebarras, nombre, fechaven, fechafab, precio);

                JOptionPane.showMessageDialog(this,
                        "Producto Creado","Registro exitoso",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "Error al ingresar datos númericos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(this,
                    "No hay espacio para guardar datos.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        catch (HeadlessException e){            
               JOptionPane.showMessageDialog(this,
                    "Error interno en el programa."+e.getMessage(),
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        finally{
            this.txtCodigodeBarras.setText("");
            this.txtNombre.setText("");
            this.txtPrecio.setText("");
            this.dcFechaVencimiento.setCalendar(null);
            this.dcFechaFabricacion.setCalendar(null);
        }
    }//GEN-LAST:event_btnCrearProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearProducto;
    private com.toedter.calendar.JDateChooser dcFechaFabricacion;
    private com.toedter.calendar.JDateChooser dcFechaVencimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigodeBarras;
    private javax.swing.JLabel lblFechafab;
    private javax.swing.JLabel lblFechaven;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigodeBarras;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
