package vista.paneles_GestionProductos;

import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Pablo Restrepo
 */
public class jpFiltrarMenorPrecio extends javax.swing.JPanel {

    private final ArrayList<clsTienda> lstTiendas;
    
    int pos = -1;
    int posi = 0;
    
    public jpFiltrarMenorPrecio(ArrayList<clsTienda> lstTiendas) {
        this.lstTiendas = lstTiendas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Filtrar menor precio");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnFiltrar.setBackground(new java.awt.Color(51, 153, 255));
        btnFiltrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        tablaProductos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Co. de barras", "Fecha de Ven.", "Fecha de Fab.", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.setEnabled(false);
        jScrollPane1.setViewportView(tablaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 430, 40));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        try{
            int menor = (int) lstTiendas.get(0).getLstProductos().get(posi).getPrecio();

            for (int i = 0; i < this.lstTiendas.get(0).getLstProductos().size(); i++) {
                if (this.lstTiendas.get(0).getLstProductos().get(i).getPrecio() < menor) {
                    menor = (int) lstTiendas.get(0).getLstProductos().get(i).getPrecio();
                    pos = 0;
                    posi = i;
                }    
            }
            Object matriz [][] = new Object[1][5];

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

            String fechafab = formato.format(this.lstTiendas.get(0).getLstProductos().get(posi).getFechaFab().getTime());
            String fechaven = formato.format(this.lstTiendas.get(0).getLstProductos().get(posi).getFechaVen().getTime());
            matriz[0][0] = this.lstTiendas.get(0).getLstProductos().get(posi).getNombre();
            matriz[0][1] = this.lstTiendas.get(0).getLstProductos().get(posi).getCodigoBarras();
            matriz[0][2] = fechaven;
            matriz[0][3] = fechafab;
            matriz[0][4] = this.lstTiendas.get(0).getLstProductos().get(posi).getPrecio();

            tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String [] {"Nombre", "Co. de barras", "Fecha de Ven.", "Fecha de Fab.", "Precio"}
            ));
        }
        catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this,
                    "Crear un producto primero.",
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
        catch (HeadlessException e){            
               JOptionPane.showMessageDialog(this,
                    "Error interno en el programa."+e.getMessage(),
                    "Validación.",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
